/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: '#f8f9ff',
          dim: '#cbdbf5',
          bright: '#f8f9ff',
          'container-lowest': '#ffffff',
          'container-low': '#eff4ff',
          container: '#e5eeff',
          'container-high': '#dce9ff',
          'container-highest': '#d3e4fe',
          variant: '#d3e4fe',
          tint: '#0053db',
        },
        'on-surface': {
          DEFAULT: '#0b1c30',
          variant: '#434655',
        },
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: {
          DEFAULT: '#737686',
          variant: '#c3c6d7',
        },
        primary: {
          DEFAULT: '#004ac6',
          on: '#ffffff',
          container: '#2563eb',
          'on-container': '#eeefff',
          inverse: '#b4c5ff',
          fixed: '#dbe1ff',
          'fixed-dim': '#b4c5ff',
          'on-fixed': '#00174b',
          'on-fixed-variant': '#003ea8',
        },
        secondary: {
          DEFAULT: '#0060ac',
          on: '#ffffff',
          container: '#64a8fe',
          'on-container': '#003c70',
          fixed: '#d4e3ff',
          'fixed-dim': '#a4c9ff',
          'on-fixed': '#001c39',
          'on-fixed-variant': '#004883',
        },
        tertiary: {
          DEFAULT: '#006242',
          on: '#ffffff',
          container: '#007d55',
          'on-container': '#bdffdb',
          fixed: '#6ffbbe',
          'fixed-dim': '#4edea3',
          'on-fixed': '#002113',
          'on-fixed-variant': '#005236',
        },
        error: {
          DEFAULT: '#ba1a1a',
          on: '#ffffff',
          container: '#ffdad6',
          'on-container': '#93000a',
        },
        background: '#f8f9ff',
        'on-background': '#0b1c30',
      },
      fontFamily: {
        heading: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '16px',
        margin: '24px',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        'level-1': '0 1px 2px 0 rgba(37, 99, 235, 0.04), 0 2px 8px 0 rgba(37, 99, 235, 0.08)',
        'level-2': '0 4px 12px 0 rgba(37, 99, 235, 0.10), 0 8px 24px 0 rgba(37, 99, 235, 0.12)',
        focus: '0 0 0 2px #004ac6',
      },
    },
  },
  plugins: [],
}
