"""add new health metrics fields

Revision ID: 0c425138fb65
Revises: b13d8c6055d3
Create Date: 2026-04-30 15:49:00.123920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c425138fb65'
down_revision: Union[str, Sequence[str], None] = 'b13d8c6055d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_metrics', sa.Column('sleep_quality', sa.String(), nullable=True))
    op.add_column('health_metrics', sa.Column('activity_minutes', sa.Integer(), nullable=True))
    op.add_column('health_metrics', sa.Column('sedentary_minutes', sa.Integer(), nullable=True))
    op.add_column('health_metrics', sa.Column('nutrition_sugar', sa.Float(), nullable=True))
    op.add_column('health_metrics', sa.Column('nutrition_fruits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_metrics', 'nutrition_fruits')
    op.drop_column('health_metrics', 'nutrition_sugar')
    op.drop_column('health_metrics', 'sedentary_minutes')
    op.drop_column('health_metrics', 'activity_minutes')
    op.drop_column('health_metrics', 'sleep_quality')
    # ### end Alembic commands ###
