"""add_lifestyle_table

Revision ID: 4588a52b8f3e
Revises: 68617a24a818
Create Date: 2026-05-02 23:23:25.611880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4588a52b8f3e'
down_revision: Union[str, Sequence[str], None] = '68617a24a818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lifestyles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tobacco_type', sa.Enum('never', 'daily', 'weekly', 'occasionally', 'former', name='tobacco_type_enum'), nullable=True),
    sa.Column('passive_smoke', sa.Boolean(), nullable=True),
    sa.Column('alcohol_freq', sa.Enum('never', 'rarely', 'sometimes', 'often', 'daily', name='alcohol_freq_enum'), nullable=True),
    sa.Column('alcohol_binge', sa.Boolean(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('work_life_balance', sa.Integer(), nullable=True),
    sa.Column('screen_time_hours', sa.Float(), nullable=True),
    sa.CheckConstraint('screen_time_hours >= 0 AND screen_time_hours <= 24', name='check_screen'),
    sa.CheckConstraint('stress_level BETWEEN 1 AND 5', name='check_stress'),
    sa.CheckConstraint('work_life_balance BETWEEN 1 AND 5', name='check_work_life'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_lifestyles_id'), 'lifestyles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lifestyles_id'), table_name='lifestyles')
    op.drop_table('lifestyles')
    # ### end Alembic commands ###
