"""add_health_metrics_table

Revision ID: 68617a24a818
Revises: 8db611f88558
Create Date: 2026-05-02 22:04:28.302220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68617a24a818'
down_revision: Union[str, Sequence[str], None] = '8db611f88558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('water_intake', sa.Float(), nullable=True),
    sa.Column('food_log', sa.JSON(), nullable=False),
    sa.Column('sleep_quality', sa.Enum('poor', 'average', 'good', 'excellent', name='sleep_quality_enum'), nullable=True),
    sa.Column('activity_minutes', sa.Integer(), nullable=True),
    sa.Column('sedentary_minutes', sa.Integer(), nullable=True),
    sa.Column('nutrition_sugar', sa.Float(), nullable=True),
    sa.Column('nutrition_fruits', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('activity_minutes >= 0 AND activity_minutes <= 1440', name='check_activity_range'),
    sa.CheckConstraint('nutrition_fruits >= 0 AND nutrition_fruits <= 20', name='check_fruits_range'),
    sa.CheckConstraint('nutrition_sugar >= 0 AND nutrition_sugar <= 500', name='check_sugar_range'),
    sa.CheckConstraint('sedentary_minutes >= 0 AND sedentary_minutes <= 1440', name='check_sedentary_range'),
    sa.CheckConstraint('sleep_hours >= 0 AND sleep_hours <= 24', name='check_sleep_range'),
    sa.CheckConstraint('steps >= 0 AND steps <= 100000', name='check_steps_range'),
    sa.CheckConstraint('water_intake >= 0 AND water_intake <= 10', name='check_water_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_user_daily_log')
    )
    op.create_index('idx_user_log_date', 'health_metrics', ['user_id', 'log_date'], unique=False)
    op.create_index(op.f('ix_health_metrics_id'), 'health_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_health_metrics_log_date'), 'health_metrics', ['log_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_metrics_log_date'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_id'), table_name='health_metrics')
    op.drop_index('idx_user_log_date', table_name='health_metrics')
    op.drop_table('health_metrics')
    # ### end Alembic commands ###
