"""add_profile_table

Revision ID: 8db611f88558
Revises: 92b328f4d876
Create Date: 2026-05-02 17:56:24.090830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db611f88558'
down_revision: Union[str, Sequence[str], None] = '92b328f4d876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('M', 'F', name='gender_enum'), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('goal', sa.Enum('Weight Loss', 'Weight Gain', 'Muscle Building', 'Maintain Fitness', 'Improve Sleep', 'Reduce Stress', name='health_goal_enum'), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.CheckConstraint('age > 0 AND age < 120', name='check_age_range'),
    sa.CheckConstraint('height > 50 AND height < 250', name='check_height_range'),
    sa.CheckConstraint('waist_cm > 30 AND waist_cm < 200', name='check_waist_cm_range'),
    sa.CheckConstraint('weight > 20 AND weight < 300', name='check_weight_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
