"""Add medical history table

Revision ID: 96dae4e3eb0f
Revises: 4588a52b8f3e
Create Date: 2026-05-03 19:51:24.986099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96dae4e3eb0f'
down_revision: Union[str, Sequence[str], None] = '4588a52b8f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diabetes', sa.Boolean(), nullable=True),
    sa.Column('bp', sa.Boolean(), nullable=True),
    sa.Column('high_cholesterol', sa.Boolean(), nullable=True),
    sa.Column('heart_disease', sa.Boolean(), nullable=True),
    sa.Column('asthma', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_medical_history_id'), 'medical_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_history_id'), table_name='medical_history')
    op.drop_table('medical_history')
    # ### end Alembic commands ###
