"""make food_log non-nullable with default

Revision ID: b2d72ff41f6d
Revises: b346f9761ed5
Create Date: 2026-04-25 18:10:27.927226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b2d72ff41f6d'
down_revision: Union[str, Sequence[str], None] = 'b346f9761ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('health_metrics', 'food_log',
               existing_type=mysql.JSON(),
               nullable=False)
    op.create_unique_constraint('uq_user_daily_log', 'health_metrics', ['user_id', 'log_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_daily_log', 'health_metrics', type_='unique')
    op.alter_column('health_metrics', 'food_log',
               existing_type=mysql.JSON(),
               nullable=True)
    # ### end Alembic commands ###
