"""add timezone to users

Revision ID: b346f9761ed5
Revises: d83891bbb90a
Create Date: 2026-04-24 23:17:41.777396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b346f9761ed5'
down_revision: Union[str, Sequence[str], None] = 'd83891bbb90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_log_date', 'health_metrics', ['user_id', 'log_date'], unique=False)
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_index('idx_user_log_date', table_name='health_metrics')
    # ### end Alembic commands ###
