"""fix

Revision ID: db576c53aa7f
Revises: 
Create Date: 2026-04-22 00:23:27.580631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db576c53aa7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_metrics', sa.Column('log_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_health_metrics_log_date'), 'health_metrics', ['log_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_metrics_log_date'), table_name='health_metrics')
    op.drop_column('health_metrics', 'log_date')
    # ### end Alembic commands ###
